# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dei\Documents\Programming\ZZZ Traffic sign THESIS\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 561)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Vid_label = QtWidgets.QLabel(self.centralwidget)
        self.Vid_label.setObjectName("Vid_label")
        self.verticalLayout.addWidget(self.Vid_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.On_cam = QtWidgets.QPushButton(self.centralwidget)
        self.On_cam.setObjectName("On_cam")
        self.verticalLayout_2.addWidget(self.On_cam)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 22))
        self.menubar.setObjectName("menubar")
        self.menuCamera = QtWidgets.QMenu(self.menubar)
        self.menuCamera.setObjectName("menuCamera")
        self.menuPreferences = QtWidgets.QMenu(self.menubar)
        self.menuPreferences.setObjectName("menuPreferences")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionHi = QtWidgets.QAction(MainWindow)
        self.actionHi.setObjectName("actionHi")
        self.actionVideo_Inference = QtWidgets.QAction(MainWindow)
        self.actionVideo_Inference.setObjectName("actionVideo_Inference")
        self.actionSet_YOLO_Model = QtWidgets.QAction(MainWindow)
        self.actionSet_YOLO_Model.setObjectName("actionSet_YOLO_Model")
        self.actionSet_ResNet50V2_Model = QtWidgets.QAction(MainWindow)
        self.actionSet_ResNet50V2_Model.setObjectName("actionSet_ResNet50V2_Model")
        self.menuCamera.addSeparator()
        self.menuCamera.addAction(self.actionRefresh)
        self.menuPreferences.addAction(self.actionVideo_Inference)
        self.menuPreferences.addSeparator()
        self.menuPreferences.addAction(self.actionSet_YOLO_Model)
        self.menuPreferences.addAction(self.actionSet_ResNet50V2_Model)
        self.menubar.addAction(self.menuPreferences.menuAction())
        self.menubar.addAction(self.menuCamera.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Vid_label.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.On_cam.setText(_translate("MainWindow", "On Cam"))
        self.menuCamera.setTitle(_translate("MainWindow", "Camera"))
        self.menuPreferences.setTitle(_translate("MainWindow", "Preferences"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))
        self.actionHi.setText(_translate("MainWindow", "Hi"))
        self.actionVideo_Inference.setText(_translate("MainWindow", "Video Inference"))
        self.actionSet_YOLO_Model.setText(_translate("MainWindow", "Set YOLO Model"))
        self.actionSet_ResNet50V2_Model.setText(_translate("MainWindow", "Set ResNet50V2 Model"))
